disabled_rules:
  - multiple_closures_with_trailing_closure # Conflict with the Xcode default style

included: 
  - SimpleApp

excluded:
  - Carthage
  - Pods

type_name:
  allowed_symbols: "_" # SwiftUI generate XXX_Previews struct 
